easy_admin:
    site_name: 'Luvaax'
    entities:
        User:
            class: Luvaax\CoreBundle\Entity\User
            label: 'Users'
            list:
                title: "Most recent users"
    design:
        menu:
            # @todo Valentin Merlet : Fix translation
            - { label: 'luvaax.menu.clear_cache', route: 'luvaax_clear_cache' }
