easy_admin:
    site_name: 'Luvaax'
    entities:
        User:
            class: Luvaax\CoreBundle\Entity\User
            label: 'Users'
            list:
                title: "Most recent users"
