easy_admin:
    site_name: 'Luvaax'
    entities:
        User:
            class: Luvaax\CoreBundle\Entity\User
            label: 'Users'
            list:
                title: "Most recent users"
            new:
                fields:
                    - username
                    - email
                    -
                        property: plainPassword
                        type: 'repeated'
                        type_options:
                            required: true
                            type: 'Symfony\Component\Form\Extension\Core\Type\PasswordType'
                            first_options: {'label': 'Password'}
                            second_options: {'label': 'Repeat password'}

                    - { property: enabled, label: 'Enabled', type_options: {data: true} }
                    -
                        property: roles
                        label: 'Roles'
                        type: 'Luvaax\CoreBundle\Form\Type\RoleSelectorType'
                        type_options: {multiple: true, expanded: true}
            edit:
                fields:
                    - username
                    - email
                    -
                        property: plainPassword
                        type: 'repeated'
                        type_options:
                            type: 'Symfony\Component\Form\Extension\Core\Type\PasswordType'
                            first_options: {'label': 'Password'}
                            second_options: {'label': 'Repeat password'}

                    - { property: enabled, label: 'Enabled' }
                    -
                        property: roles
                        label: 'Roles'
                        type: 'Luvaax\CoreBundle\Form\Type\RoleSelectorType'
                        type_options: {multiple: true, expanded: true}
