luvaax_core:
    resource: "@LuvaaxCoreBundle/Controller/"
    type:     annotation
    prefix:   /

luvaax_:
    resource: "@LuvaaxCoreBundle/Resources/config/routing.yml"
    prefix:   /

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
