luvaax_core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
