luvaax_theme:
    resource: "@LuvaaxThemeBundle/Controller/"
    type:     annotation
    prefix:   /

luvaax_core:
    resource: "@LuvaaxCoreBundle/Controller/"
    type:     annotation
    prefix:   /

luvaax_theme:
    resource: "@LuvaaxThemeBundle/Controller/"
    type:     annotation
    prefix:   /

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

umanit_tree:
    resource: "@UmanitTreeBundle/Resources/config/routing.yml"
    prefix:   /
