services:
    luvaax.core.form.role_selector:
        class: Luvaax\CoreBundle\Form\Type\RoleSelectorType
        arguments:
            - '@luvaax.core.role_manager'
        tags:
            - { name: form.type }
