services:
   luvaax.core.user_subscriber:
       class: Luvaax\CoreBundle\Subscriber\UserSubscriber
       arguments:
           - '@security.password_encoder'
       tags:
           - { name: kernel.event_subscriber }

   luvaax.core.field_type_subscriber:
       class: Luvaax\CoreBundle\Event\Listener\FieldTypeSubscriber
       tags:
           - { name: kernel.event_subscriber }
